# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3706af4168fcd83ae3cddac8849c3589dd07867fcc9e7e042e07d147e8cf2cfdedc1deca61a425da8f97fb64583790fb1dc622160be41b696710727a8ab3ffec

test:
  secret_key_base: 6d048898c26326d752edf02df082a431e64dd3c0c263ea3291d4bf985f7fc292015a25ac060908c9b7115caf31f4cf97a339e737ba821c1442ff4fa5b29b3423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
